apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-firefox-scaledobject
  namespace: selenium
  labels:
    deploymentName: selenium-node-firefox
spec:
  minReplicaCount: 1
  maxReplicaCount: 10
  scaleTargetRef:
    name: selenium-node-firefox
  triggers:
    - type: selenium-grid
      metadata:
        url: 'http://a06768e1831454a65bf258ea8df0d23d-233233995.us-east-2.elb.amazonaws.com:4444/graphql'  #this is selenium grid URL, external IP of Loadbalancer
        browserName: 'firefox'